# Deploy to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: demo

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Deploy to gh-pages
        run: |
          git checkout -b gh-pages-temp
          git branch -D gh-pages || true
          git checkout --orphan gh-pages
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force 